name: Update from Home Assistant Core and create a HACS version
run-name: Updating from Home Assistant Core and create a HACS version...
on: workflow_dispatch
jobs:
  from_core_to_hacs:
      runs-on: self-hosted
      steps:
          - run: echo "Downloading..."
          - uses: actions/checkout@main
            with:
              name: https://github.com/DevPocket/homeassistant-core.git
              ref: refs/heads/domika_integration
          - run: echo "Removing old sources..."
          # - run: rm -r tests
          # - run: ls
